max_epoch: 500 #
batch_size: 8 #4 #10 #同kpconv中的batch_num
base_learning_rate: 0.01 #2卡：0.004 #kpconv中的learning_rate #0.01
optimizer: 'sgd' #
momentum: 0.98 #
# decay_rate: 0.9885531
#decay_epoch: 1
#lr_decays: {i: 0.1**(1/100) for i in range(1,max_epoch)}

decay_rate: 0.9772372209558107 #0.1**(1/100) #0.9885531
decay_epoch: 1
first_subsampling_dl: 0.04 #
density_parameter: 5.0 #
activation_fn: 'relu'
init: 'xavier'
bn_eps: 0.000001
weight_decay: 0.001
grad_norm: 100 #同grad_clip_norm
in_features_dim: 4  #  #5
bottleneck_ratio: 2
first_features_dim: 64 #        #72
local_aggreagtion: 'pseudo_grid' #kpconv没有这个
pseudo_grid: #kpconv没有这个
  fixed_kernel_points: 'center'
  KP_influence: 'linear' #
  KP_extent: 1.0 #
  num_kernel_points: 15 #
  convolution_mode: 'sum' #
  output_conv: False


epoch_steps: 600 #
validation_size: 50 #
in_radius: 2.0 #
augment_scale_anisotropic: True #
augment_symmetries: #
  - True
  - False
  - False
augment_rotation: 'vertical' #
augment_scale_min: 0.9 #
augment_scale_max: 1.1 #
augment_noise: 0.001 #
augment_color: 1.0 #

#下面为自己额外添加
# augment_occlusion : 'none'
# # Number of epoch between each snapshot
# snapshot_gap : 50
# # Batch normalization parameters
# use_batch_norm : True
# batch_norm_momentum : 0.98
# # 'permissive' only constrains offsets inside the big radius 
# # 'fitting' helps deformed kernels to adapt to the geometry by penalizing distance to input points
# offsets_loss : 'fitting'
# offsets_decay : 0.1
# # Can the network learn modulations
# modulated : False

#augment_symmetries = [True, False, False]

